// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCxnmg0d-6gm8N9fXDotMp21DIeE_Dg_tE',
    appId: '1:1012529805143:web:712132ec06ac7568727012',
    messagingSenderId: '1012529805143',
    projectId: 'stemm-assignment',
    authDomain: 'stemm-assignment.firebaseapp.com',
    storageBucket: 'stemm-assignment.appspot.com',
    measurementId: 'G-4R09Q7RSJ4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDU9H2Y6QhADyxVfF0LzA7Dfv5rJjm8DFw',
    appId: '1:1012529805143:android:ec4c4b1ef2a18578727012',
    messagingSenderId: '1012529805143',
    projectId: 'stemm-assignment',
    storageBucket: 'stemm-assignment.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBBPixM3PP4Dhmq25tD6S8KhJc7XTeAKUk',
    appId: '1:1012529805143:ios:c6b6b493acb0b55c727012',
    messagingSenderId: '1012529805143',
    projectId: 'stemm-assignment',
    storageBucket: 'stemm-assignment.appspot.com',
    iosBundleId: 'com.flutterwings.stemmCloudwoorkAssignment',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBBPixM3PP4Dhmq25tD6S8KhJc7XTeAKUk',
    appId: '1:1012529805143:ios:beb45809c98405f5727012',
    messagingSenderId: '1012529805143',
    projectId: 'stemm-assignment',
    storageBucket: 'stemm-assignment.appspot.com',
    iosBundleId: 'com.flutterwings.stemmCloudwoorkAssignment.RunnerTests',
  );
}
